server:
  port: 8080
spring:
  profiles:
    active: ${SPRING_PROFILES_INCLUDE:dev}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://127.0.0.1:8888}
  cloud:
    config:
      label: ${SPRING_CLOUD_CONFIG_LEVEL:master}
      username: ${SPRING_CLOUD_CONFIG_USERNAME:geek_user}
      password: ${SPRING_CLOUD_CONFIG_PASSWORD:geek_pass}

  artemis:
    user: 'admin'
    password: 'admin'

#logging:
#  level:
#    root: DEBUG


#  datasource:
#    url: "jdbc:postgresql://localhost:5432/gb_shop"
#    username: "geek"
#    password: "geek"
# /{label}/{application}-{profile}.yml
# /{application}/{profile}/{label}
